name: Daily Predictions

on:
  schedule:
    # Run at 4:30 PM EST (9:30 PM UTC) every day
    - cron: '30 21 * * *'
  workflow_dispatch:  # Allow manual trigger

env:
  ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}

jobs:
  predict:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Generate predictions
        run: python src/predict.py
      
      - name: Generate WizardofOdds feed
        run: python src/generate_feed.py
      
      - name: Commit predictions
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add prediction files
          git add predictions/
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No new predictions to commit"
          else
            git commit -m "ðŸ€ Daily predictions - $(date +'%Y-%m-%d')"
            git push
          fi
      
      - name: Upload prediction artifacts
        uses: actions/upload-artifact@v4
        with:
          name: predictions-${{ github.run_number }}
          path: predictions/
          retention-days: 90
      
      - name: Post summary to job
        run: |
          echo "## ðŸ€ Today's Predictions Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          python src/summary.py >> $GITHUB_STEP_SUMMARY
